# -*- coding: utf-8 -*-
"""Aviation Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hC4Z0dIlrieyj5SNyO4mk5QTtDvuPB2D
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load your data
df = pd.read_csv("Aviation.csv")

# Convert Date to datetime
df['Date'] = pd.to_datetime(df['Date'] + ' 2025', format="%d %B %Y")

# Manually define the crash date
crash_date = pd.to_datetime("12 June 2025", format="%d %B %Y")

# Set style
sns.set(style="whitegrid", context="talk")
plt.figure(figsize=(14, 7))



# Plot stock prices
plt.plot(df['Date'], df['Boeing'], label='Boeing', color='red', linewidth=2)
plt.plot(df['Date'], df['Airbus'], label='Airbus', color='blue', linewidth=2)

# Vertical crash line
plt.axvline(crash_date, color='black', linestyle='--', linewidth=1.5, label='Crash: 12 June 2025')

# Shaded post-crash period
plt.axvspan(crash_date, df['Date'].max(), color='gray', alpha=0.1)

# Annotate crash impact
plt.annotate('Crash Day\n↓ Boeing drops\n↑ Airbus rises',
             xy=(crash_date, df.loc[df['Date'] == crash_date, 'Boeing'].values[0]),
             xytext=(crash_date, df['Boeing'].max() + 5),
             arrowprops=dict(arrowstyle="->", color='black'),
             fontsize=12,
             ha='center')

# Title & labels
plt.title("Impact of 12 June Air India Crash on Boeing and Airbus Stocks", fontsize=12)
plt.xlabel("Date")
plt.ylabel("Stock Price")
plt.xticks(rotation=45)
plt.legend()
plt.tight_layout()
plt.show()



import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load your data
df = pd.read_csv("Aviation.csv")

# Convert Date to datetime
df['Date'] = pd.to_datetime(df['Date'] + ' 2025', format="%d %B %Y")

# Manually define the crash date
crash_date = pd.to_datetime("12 June 2025", format="%d %B %Y")

# Set style
sns.set(style="whitegrid", context="talk")
plt.figure(figsize=(14, 7))

#convert Airbus price to USD
EUR_TO_USD = 1.08
df['Airbus_USD'] = df['Airbus'] * EUR_TO_USD


# Plot stock prices
plt.plot(df['Date'], df['Boeing'], label='Boeing', color='red', linewidth=2)
plt.plot(df['Date'], df['Airbus_USD'], label='Airbus (converted to USD)', color='blue', linewidth=2)

# Vertical crash line
plt.axvline(crash_date, color='black', linestyle='--', linewidth=1.5, label='Crash: 12 June 2025')

# Shaded post-crash period
plt.axvspan(crash_date, df['Date'].max(), color='gray', alpha=0.1)

# Annotate crash impact
plt.annotate('Crash Day\n↓ Boeing drops\n↑ Airbus rises',
             xy=(crash_date, df.loc[df['Date'] == crash_date, 'Boeing'].values[0]),
             xytext=(crash_date, df['Boeing'].max() + 5),
             arrowprops=dict(arrowstyle="->", color='black'),
             fontsize=12,
             ha='center')

# Title & labels
plt.title("Impact of 12 June Air India Crash on Boeing and Airbus Stocks", fontsize=12)
plt.xlabel("Date")
plt.ylabel("Stock Price")
plt.xticks(rotation=45)
plt.legend()
plt.tight_layout()
plt.show()